### PR TITLE
Automated Syntax correction and enforcement

### PR DESCRIPTION
**Pull request by huitseeker**
Please refer to https://github.com/deeplearning4j/nd4j/pull/1626 — this is the same idea applied to a different repo.
Enforces https://google.github.io/styleguide/javaguide.html

I'll just repeat how you can get automated formatting in case of an issue:
- run 'mvn formatter:format' in any subproject you want
- use the IDEA plugin https://plugins.jetbrains.com/idea/plugin/8527-google-java-format
- use Eclipse's built-in code formatter with the provided contrib/formatter.xml format file
- if all else fails, replace in the root pom the goal of the mvn-formatter-plugin :
  <goal>validate</goal>
  with
  <goal>format</goal>

### CODE REVIEW

**Comment by huitseeker** [comment]
Forgot a file, do not merge

**Comment by huitseeker** [comment]
I can remove the enforcement for now, if need be.

**Comment by agibsonccc** [comment]
Yeah just concerned about how we "onboard" this. We should fix all the enforcement errors in this branch before merging this.Yeah just concerned about how we "onboard" this. We should fix all the enforcement errors in this branch before merging this.

**Comment by huitseeker** [comment]
All the enforcement errors are fixed in 2850231, otherwise I would not have submitted the PR.

**Comment by huitseeker** [comment]
Rather than maintaining this, I'd rather merge the corrections without the enforcement and have a later PR for enforcement.

**Pull request merged**
