### PR TITLE
WIP: Fix for failing LibSvm and SVMLight unit tests 

### PR DESCRIPTION
**Pull request by turambar**
## What changes were proposed in this pull request?

Switched direction of a sign in a unit test. Really stupid.

## How was this patch tested?

Existing unit tests now pass.

Please review
https://github.com/deeplearning4j/deeplearning4j/blob/master/CONTRIBUTING.md before opening a pull request.

### CODE REVIEW

**Comment by turambar** [comment]
Hey @AlexDBlack @saudet @huitseeker, I totally forgot, but I left some TODOs in the code where we should throw an exception, but I wanted your feedback on what type of exception to throw and --
 if we need to add a new type of exception -- whether it's OK to propagate the exception all the way up to the RecordReader interface, which I imagine would require changing all of the implementations.

- https://github.com/deeplearning4j/DataVec/blob/3b9765847523af9e887006f4a379eb64373c3eab/datavec-api/src/main/java/org/datavec/api/records/reader/impl/misc/LibSvmRecordReader.java#L100
- https://github.com/deeplearning4j/DataVec/blob/3b9765847523af9e887006f4a379eb64373c3eab/datavec-api/src/main/java/org/datavec/api/records/reader/impl/misc/LibSvmRecordReader.java#L123
- https://github.com/deeplearning4j/DataVec/blob/3b9765847523af9e887006f4a379eb64373c3eab/datavec-api/src/main/java/org/datavec/api/records/reader/impl/misc/SVMLightRecordReader.java#L90
- https://github.com/deeplearning4j/DataVec/blob/3b9765847523af9e887006f4a379eb64373c3eab/datavec-api/src/main/java/org/datavec/api/records/reader/impl/misc/SVMLightRecordReader.java#L114

**Comment by saudet** [comment]
There is already a perfectly fine IndexOutOfBoundsException for that. I'd personally just go with that.

**Comment by huitseeker** [comment]
https://github.com/deeplearning4j/DataVec/pull/282/files#r118094747
I concur with the `IndexOutOfBoundsException`.

**Comment by huitseeker** [comment]
Any news @turambar ? It would be great if we could close those failing tests soon.

**Comment by huitseeker** [comment]
Merging with thrown exceptions corrections to fix tests, feel free to edit message to your taste later, @turambar .

**Pull request merged**
