### PR TITLE
Add RecordMetaDataImageURI and NativeImageLoader.asMat()/asFrame()

### PR DESCRIPTION
**Pull request by saudet**
## What changes were proposed in this pull request?

New functionality that is useful for object detection.

## How was this patch tested?

New unit tests pass and manually testing with example code also works as intended.

### CODE REVIEW

**Comment by saudet** [comment]
We're just adding information to the metadata. The URI stays the same, so it should load the same. Am I missing something?

**Comment by AlexDBlack** [comment]
Yeah, the labels though. If we don't override loadFromMetaData, then we end up calling BaseImageRecordReader.record(URI, DataInputStream), which will create an IntWritable label, instead of an NDArrayWritable label.

https://github.com/deeplearning4j/DataVec/blob/master/datavec-data/datavec-data-image/src/main/java/org/datavec/image/recordreader/BaseImageRecordReader.java#L404-L434

**Comment by saudet** [comment]
Ok, it's done!

**Comment by saudet** [comment]
Yes, we need it for the tests to pass with current ND4J...

**Pull request merged**
