### PR TITLE
forcing Content-Type to application/json

### LINKED ISSUE #427: Wrong Content-Type Header
#### Issue Description

[`CSVSparkTransformServer`](https://github.com/deeplearning4j/DataVec/blob/master/datavec-spark-inference-parent/datavec-spark-inference-server/src/main/java/org/datavec/spark/transform/CSVSparkTransformServer.java) no longer returns the `Content-Type` header as `application/json` but rather as `text/plain`. Looks like perhaps the changes in #418 introduced this.

#### Version Information

Please indicate relevant versions, including, if relevant:

`master` as of this submission (ee923b0f5f39f1c8e85f9bc480efdf7416565f6a)

### PR DESCRIPTION
**Pull request by emsixteeen**
## What changes were proposed in this pull request?

Fixes #427

### CODE REVIEW

**Comment by emsixteeen** [comment]
I don't disagree ... it was like that originally (prior to #418). I don't know the history / context as to why it was changed. 

This simply fixes the the `Content-Type` issue so that clients that expect to the `Content-Type` type to be `application/json` (such as Spring `RestTemplate`) can continue to work as before.

**Comment by agibsonccc** [comment]
I'm ok with this for now.  @huitseeker We would have to overhaul all of our json object handling at some point anyways. This single PR isn't the time to do that.

**Comment by emsixteeen** [comment]
Can someone please merge this? Pretty please ...

**Pull request merged**
